# x86-64 AT&T Assembly — generated by tcg.c
# Compiler Design Project | GEU
# Assemble: gcc -no-pie output.s -o <output>

.section .data
.section .text

# ─────────────────────────────────────────
# Function: main  (frame = 16 bytes)
# ─────────────────────────────────────────
    .globl main
    .type  main, @function
main:
    pushq %rbp
    movq  %rsp, %rbp
    subq  $16, %rsp
    # spill incoming args (if any)
    # return 42
    movq  $42, %rax
    leave
    ret
    # epilogue — main
    leave
    ret
    .size main, .-main

